name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set Git identity
        run: |
          git config --global user.name "Raju Sharma"
          git config --global user.email "rajusharmadata@gmail.com"

      - name: Deploy
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npx gh-pages -d dist -r https://x-access-token:${TOKEN}@github.com/rajusharmadata/cicd-testing.git
